.PHONY: all init generate clean

all: init generate

init: 
	@echo "Start to execute Makefile ..."

generate: 
	@echo "Creating a file named README.md ..."
	touch README.md

clean: 
	@echo "Cleaning up..."
	rm *.md
